Repository jenkinsci/commons-text-api-plugin, pull requests merged in 2023-08, with the labels that each got.

#40 Modernize to Jenkins 2.375.4
  pom.xml
Labels: dependencies, maintenance

#41 Build on JDK 21
  Jenkinsfile
Labels: maintenance

#43 Add plugin developer team to CODEOWNERS
  .github/CODEOWNERS
Labels: skip-changelog
